# MitM
hostname = edith.xiaohongshu.com

# 笔记详情接口
^https?://edith\.xiaohongshu\.com/api/sns/v2/note/info url script-response-body https://raw.githubusercontent.com/ytywxw/quanx/main/JS/xhs/noWatermark.js
# 信息流feed接口
^https?://edith\.xiaohongshu\.com/api/sns/v1/feed url script-response-body https://raw.githubusercontent.com/ytywxw/quanx/main/JS/xhs/noWatermark.js