# MitM
hostname = *.yaolaoss.cn

# 解锁搜索次数
^https://www\.yaolaoss\.cn/Appapi/ApiCert/ifUserSearchID\.html url response-body status":"false response-body status":"true
# 关闭访问足迹
^https://www\.yaolaoss\.cn/Appapi/ApiMain/getUserInfo\.html url request-body createid%22%3A%22\d+%22 request-body createid%22%3A%22%22
# 解锁会员
^https://www\.yaolaoss\.cn/Appapi/ApiMyself/getMyselfInfo\.html url script-response-body https://raw.githubusercontent.com/ytywxw/quanx/main/JS/ylss/getMyselfInfo.js
# 详情页增加真实姓名显示，生日显示，星座显示，注销账号显示
^https://www\.yaolaoss\.cn/Appapi/ApiMain/getUserInfo\.html url script-response-body https://raw.githubusercontent.com/ytywxw/quanx/main/JS/ylss/getUserInfo.js
# 推荐页增加生日显示
^https://www\.yaolaoss\.cn/Appapi/ApiMain/getRecommend\.html url script-response-body https://raw.githubusercontent.com/ytywxw/quanx/main/JS/ylss/getRecommend.js